[package]
name = "dora-primitives"
version.workspace = true
edition.workspace = true

[dependencies]
revm.workspace = true

serde = { version = "1.0", features = ["derive", "rc"] }
alloy-primitives = "1.5.3"
indexmap = "2.13.0"
