[package]
name = "dora-primitives"
version = "0.1.0"
edition = "2021"

[dependencies]
ethereum-types = "0.14.1"
bytes = { version = "1.6.0", features = ["serde"] }
thiserror = "1.0.63"
sha3 = "0.10.8"
bitflags = "2.6.0"
