[package]
name = "dora"
version.workspace = true
edition.workspace = true

[dependencies]
dora-compiler.workspace = true
dora-primitives.workspace = true
dora-runtime.workspace = true
dora-ir.workspace = true

hex = "0.4.3"
anyhow = "1.0.96"
hex-literal = "1.0.0"
num-bigint = "0.4.5"

[dev-dependencies]
wasmer = "5.0.4"
alloy-sol-types = { version = "0.8.2", default-features = false, features = [
    "std",
] }
